- name: "Install PostgreSQL yum"
  ansible.builtin.yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - postgresql
    - postgresql-server
    - python-psycopg2
    - python-ipaddress

- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "Start and enable services"
  service:
    name: postgresql
    state: started
    enabled: true

- name: "Create app database"
  postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: true
  become_user: postgres

- name: "Create db user"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all
  become: true
  become_user: postgres

- name: "Allow password connection for the db user"
  postgresql_pg_hba:
    dest: "/var/lib/pgsql/data/pg_hba.conf"
    contype: host
    databases: all
    method: password
    users: "{{ db_user }}"
    create: true
  become: true
  become_user: postgres

- name: "Restart PostgreSQL"
  service:
    name: postgresql
    state: restarted
