- name: "Install app dependencies"
  ansible.builtin.yum: 
    name: 
      - "@development-tools"
      - libxml2-devel
      - libxslt-devel
      - git
      - postgresql-devel
      - nodejs
      - ruby-devel
    state: latest 
    update_cache: yes

- name: "Check if we are having app directories"
  stat:
    path: /apps/{{app_name}}
  register: app_files

- name: "Copy application files from git"
  ansible.builtin.git:
    repo: "https://{{ username | urlencode }}:{{ password | urlencode }}@gitlab.slurm.io/edu/xpaste_practicum.git"
    dest: /apps/{{app_name}}
  when: not app_files.stat.exists

- name: "Install app with bundler module"
  community.general.bundler:
    state: present
    deployment_mode: yes
    chdir: /apps/{{app_name}}
    executable: /usr/local/bin/bundle
    extra_args: --clean --no-cache
    exclude_groups: development

- name: "Check if we are having app directories"
  stat:
    path: /etc/systemd/system/{{app_name}}.service
  register: service_file

- name: "Copy a service file"
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/{{app_name}}.service
  when: not service_file.stat.exists

- name: "Start app service"
  systemd:
    name: xpaste_practicum
    state: started
    enabled: true
    daemon_reload: true

- name: "Copy a nginx.conf file"
  ansible.builtin.copy:
    src: /apps/{{app_name}}/config/nginx.conf
    dest: /etc/nginx/nginx.conf
    remote_src: true

- name: "Copy a robots.txt file"
  ansible.builtin.copy:
    src: /apps/{{app_name}}/public/robots.txt 
    dest: /apps/{{app_name}}/app/assets/robots.txt
    remote_src: true

- name: "Replace nginx.conf path"
  shell: sed -i 's+/app/public+/apps/xpaste_practicum/app/assets+' /etc/nginx/nginx.conf

 
